// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dispatch(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Dispatch'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function RequestExit() {
  return window['go']['backend']['App']['RequestExit']();
}

export function SetDevToolsState(arg1) {
  return window['go']['backend']['App']['SetDevToolsState'](arg1);
}

export function SetTrayIcon(arg1) {
  return window['go']['backend']['App']['SetTrayIcon'](arg1);
}

export function ToggleDevTools() {
  return window['go']['backend']['App']['ToggleDevTools']();
}
