// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';

export function Dispatch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RequestExit():Promise<void>;

export function SetDevToolsState(arg1:boolean):Promise<void>;

export function SetTrayIcon(arg1:Array<number>):Promise<void>;

export function SingleInstanceLock():Promise<options.SingleInstanceLock>;

export function ToggleDevTools():Promise<void>;
